management:
  endpoint:
    health:      
      enabled: true
    env:      enabled: true
    refresh:      enabled: true
    beans:      enabled: true
  endpoints:
    web:      
      exposure:        
        include:        
        - info
        - env
        - refresh
        - beans
        - loggers
